version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    user: $UIDusesdsd
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: Reviews
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      -  ./data:/data/db
      -  /mongo-init.sh:/docker-entrypoint-initdb.d/mongoinit-sh:ro
    ports:
      - "27017:27017"