version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      -  ./data:/data/db
      -  /mongo-init.sh:/docker-entrypoint-initdb.d/mongoinit-sh:ro
    ports:
      - "27017:27017"